name: 'Build, Push and Release Docker Image'
description: 'This action builds and pushes container images and creates a GitHub release if the workflow was triggered by a pushed tag starting with "v"'
inputs:
  tags:
    description: 'Container Image Tags'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: src/main/docker/Dockerfile.jvm
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
